### ISSUE TITLE
No warning when navigating back while creating a new route

### ISSUE THREAD

**Issue by gregersrygg** [randopedia/randopedia#1]
Looks like the warning is only when [editing an existing route](https://github.com/randopedia/randopedia/blob/master/randopedia-web/src/routes.js#L156). Not sure how to best implement it for TourNewRoute in a clean way.

I was drawing a route, but had too many points, so tried different usual keyboard-buttons for deleting the last created point. When clicking <kbd>←</kbd> I navigated back to the previous page and lost the description and everything else :(

**Comment by bjoda** [comment]
Can confirm the issue. Will look into it..

**Comment by bjoda** [comment]
Fixed.

**Comment by gregersrygg** [comment]
:dancer: :smile:

**Comment by bjoda** [comment]
Snabbt fixat va! :)

**Comment by gregersrygg** [comment]
Bedre sent enn aldri ;)
